name: build_app
on:
  workflow_dispatch:
    inputs:  
      branch_name:
        # add the branch name
        description: 'Branch name'
        required: true
        default: ''
      
      deploy_env:
        # add the deployment environment
        description: 'Deployment Environment'
        required: true
        default: ''

jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: export variables
        id: vars
        shell: bash
        run: |
          export AWS_DEFAULT_REGION='us-east-1'
          BRANCH_NAME=${{ github.event.inputs.branch_name }}
          DEPLOY_ENVIRONMENT=${{ github.event.inputs.deploy_env }}
          
          if [[ ${BRANCH_NAME} == "develop" ]] || [[ ${BRANCH_NAME} == "direct-develop" ]] || [[ ${BRANCH_NAME} == "direct-int" ]] || [[ ${BRANCH_NAME} =~ ^feature.*$ ]] || [[ ${BRANCH_NAME} =~ ^bugfix.*$ ]]; then
            echo "AWS_PROFILE=dev" >> $GITHUB_OUTPUT
            echo "ENV_NAME=dev" >> $GITHUB_OUTPUT

          elif [[ ${BRANCH_NAME} =~ ^release\-[0-9]*\.[0-9]*\.[0-9]*$ ]]; then

            echo "AWS_PROFILE=qa" >> $GITHUB_OUTPUT
            echo "ENV_NAME=qa" >> $GITHUB_OUTPUT

          elif [[ ${BRANCH_NAME} = "master" ]]; then
            echo "AWS_PROFILE=prod" >> $GITHUB_OUTPUT
            echo "ENV_NAME=prod" >> $GITHUB_OUTPUT

          else
            echo "No branch selected"
          fi

          if [[ ${DEPLOY_ENVIRONMENT} == 'dev' ]]; then
            echo "AWS_PROFILE=dev" >> $GITHUB_OUTPUT
            echo "ENV_NAME=dev" >> $GITHUB_OUTPUT
            echo "ROLE_ARN=arn:aws:iam::1:role/Deployer" >> $GITHUB_OUTPUT

          elif [[  ${DEPLOY_ENVIRONMENT} == 'qa' ]]; then
            echo "AWS_PROFILE=qa" >> $GITHUB_OUTPUT
            echo "ENV_NAME=qa" >> $GITHUB_OUTPUT
            echo "ROLE_ARN=arn:aws:iam::2:role/Deployer" >> $GITHUB_OUTPUT

          elif [[ ${DEPLOY_ENVIRONMENT} == 'prod' ]]; then
            echo "AWS_PROFILE=prod" >> $GITHUB_OUTPUT
            echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
            echo "ROLE_ARN=arn:aws:iam::3:role/Deployer" >> $GITHUB_OUTPUT

          else
            echo "No environment selected."
          fi
          
      - name: initialization
        shell: bash
        run: |
          echo ${{ steps.vars.outputs.AWS_PROFILE }}
          echo ${{ steps.vars.outputs.ENV_NAME }}
          WORK_DIR=$(pwd)
          export WORK_DIR

          function install_dependencies(){
              echo "Install NPM dependencies"
              npm install
          }

          install_dependencies
          
      - name: npm validation
        run: |
          #!/bin/bash
          function validate_sam_template(){
              echo "Validate SAM.yaml template"
              npm run validate:sam
          }

          function lint_code(){
              echo "Verify code style quality"
              npm run lint
          }

          validate_sam_template
          lint_code
          
      - name: npm build
        run: |
          #!/bin/bash
          function build_lambdas(){
              echo "Build lambdas"
              npm run build:lambda
          }

          build_lambdas
          
      - name: npm test
        run: |
          #!/bin/bash
          function unit_tests(){
              echo "Run unit tests"
              npm run test:unit
          }

          unit_tests
          
      - name: npm s3 upload
        run: |
          #!/bin/bash
          function upload_files_to_s3() {
              echo "Uploading API definition to S3 bucket"
              npm run "upload:api:${ENV_NAME}"
          }

          upload_files_to_s3
          
